# Generated by Django 3.2.7 on 2021-11-24 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='avatar',
            new_name='profile_image',
        ),
    ]
