# Generated by Django 3.2.7 on 2021-11-24 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile1', '0003_alter_profile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(default='default.png', upload_to=''),
        ),
    ]
